name: mobile
description: Portal Rick and Morty em Flutter.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Bricolage Grotesque
      fonts:
        - asset: fonts/BricolageGrotesque.ttf
    - family: Atkinson Hyperlegible
      fonts:
        - asset: fonts/AtkinsonHyperlegible-Regular.ttf
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBMPlexMono-Regular.ttf
